const {
  spawn
} = require('child_process');
const images = [
  // '#abacas',
  // '#abased',
  // '#abases',
  // '#abbess',
  // '#abcess',
  // '#abeles',
  // '#abesse',
  // '#aboded',
  // '#abodes',
  // '#abolla',
  // '#accede',
  // '#access',
  // '#accoll',
  // '#acoela',
  // '#addled',
  // '#addles',
  // '#adelea',
  // '#adless',
  // '#adobes',
  // '#adobos',
  // '#aefald',
  // '#afaced',
  // '#afocal',
  // '#alasas',
  // '#albedo',
  // '#alcade',
  // '#alcedo',
  // '#alclad',
  // '#aldols',
  // '#aldose',
  // '#allele',
  // '#allods',
  // '#allose',
  // '#aloofe',
  // '#aloose',
  // '#ascebc',
  // '#assbaa',
  // '#asseal',
  // '#asself',
  // '#assess',
  // '#babble',
  // '#babels',
  // '#babool',
  // '#baboos',
  // '#bacaba',
  // '#baccae',
  // '#badass',
  // '#baffed',
  // '#baffle',
  // '#balada',
  // '#balafo',
  // '#balaos',
  // '#balboa',
  // '#balded',
  // '#ballad',
  // '#ballas',
  // '#balled',
  // '#balolo',
  // '#balsas',
  // '#baobab',
  // '#basale',
  // '#basses',
  // '#bassos',
  // '#beaded',
  // '#beadle',
  // '#bebled',
  // '#beboss',
  // '#becall',
  // '#beclad',
  // '#bedaff',
  // '#bedded',
  // '#bedead',
  // '#bedeaf',
  // '#bedell',
  // '#bedels',
  // '#beebee',
  // '#beefed',
  // '#beelol',
  // '#befall',
  // '#befell',
  // '#beflea',
  // '#befool',
  // '#belace',
  // '#beleaf',
  // '#beleed',
  // '#belled',
  // '#belles',
  // '#bescab',
  // '#beslab',
  // '#bessel',
  // '#besses',
  // '#bladed',
  // '#blades',
  // '#bleeds',
  // '#blesse',
  // '#bloods',
  // '#bobbed',
  // '#bobble',
  // '#bocces',
  // '#boddle',
  // '#boffos',
  // '#bolded',
  // '#boldos',
  // '#bolled',
  // '#boloed',
  // '#booboo',
  // '#boodle',
  // '#bossed',
  // '#bosses',
  // '#cabala',
  // '#caball',
  // '#cabals',
  // '#cabasa',
  // '#cabbed',
  // '#cabble',
  // '#cabled',
  // '#cables',
  // '#cabobs',
  // '#cacaos',
  // '#cadded',
  // '#caddle',
  // '#caecal',
  // '#caffle',
  // '#calaba',
  // '#calade',
  // '#calced',
  // '#calces',
  // '#calesa',
  // '#callas',
  // '#called',
  // '#calles',
  // '#calloo',
  // '#calool',
  // '#casaba',
  // '#casabe',
  // '#cascol',
  // '#ceased',
  // '#ceases',
  // '#cebell',
  // '#celebe',
  // '#celebs',
  // '#cellae',
  // '#celled',
  // '#cellos',
  // '#cessed',
  // '#cesses',
  // '#cledde',
  // '#cloaca',
  // '#closed',
  // '#closes',
  // '#coalas',
  // '#coaled',
  // '#cobaea',
  // '#cobbed',
  // '#cobble',
  // '#cobcab',
  // '#cobles',
  // '#cobola',
  // '#coboss',
  // '#coccal',
  // '#coclea',
  // '#cocoas',
  // '#codded',
  // '#coddle',
  // '#codecs',
  // '#coecal',
  // '#coffea',
  // '#coffee',
  // '#coffle',
  // '#colada',
  // '#collab',
  // '#colola',
  // '#coloss',
  // '#cooboo',
  // '#coodle',
  // '#cooeed',
  // '#cooees',
  // '#cooled',
  // '#cosecs',
  // '#cossas',
  // '#dabbed',
  // '#dabble',
  // '#dacelo',
  // '#daddle',
  // '#dadoed',
  // '#dadoes',
  // '#daedal',
  // '#daffed',
  // '#daffle',
  // '#dallas',
  // '#dalles',
  // '#dclass',
  // '#debase',
  // '#debcle',
  // '#debell',
  // '#deboss',
  // '#decade',
  // '#decals',
  // '#decede',
  // '#decess',
  // '#decode',
  // '#decoll',
  // '#deeded',
  // '#deeses',
  // '#deface',
  // '#defade',
  // '#deflea',
  // '#delace',
  // '#delead',
  // '#deseed',
  // '#desole',
  // '#doable',
  // '#dobbed',
  // '#doblas',
  // '#dodded',
  // '#doddle',
  // '#dodoes',
  // '#doffed',
  // '#doless',
  // '#dolled',
  // '#dolose',
  // '#doodab',
  // '#doodad',
  // '#doodle',
  // '#doolee',
  // '#dossal',
  // '#dossed',
  // '#dossel',
  // '#dosses',
  // '#easels',
  // '#eassel',
  // '#ebcasc',
  // '#ecbole',
  // '#eccles',
  // '#ecoles',
  // '#eddoes',
  // '#eelbob',
  // '#efface',
  // '#elodea',
  // '#elodes',
  // '#escoba',
  // '#esseda',
  // '#essede',
  // '#fabled',
  // '#fables',
  // '#facade',
  // '#faddle',
  // '#faecal',
  // '#faeces',
  // '#faffle',
  // '#falces',
  // '#fallal',
  // '#fasces',
  // '#fasels',
  // '#fasola',
  // '#feased',
  // '#feases',
  // '#feeble',
  // '#feeded',
  // '#fellas',
  // '#felled',
  // '#felloe',
  // '#feodal',
  // '#feoffs',
  // '#fesels',
  // '#fessed',
  // '#fesses',
  // '#flabel',
  // '#fleece',
  // '#floods',
  // '#flossa',
  // '#foaled',
  // '#fobbed',
  // '#focsle',
  // '#folded',
  // '#folles',
  // '#fooled',
  // '#fossae',
  // '#fossed',
  // '#fosses',
  // '#labels',
  // '#lablab',
  // '#laccol',
  // '#lacoca',
  // '#ladled',
  // '#ladles',
  // '#lalled',
  // '#lasses',
  // '#lassos',
  // '#leaded',
  // '#leafed',
  // '#leased',
  // '#leases',
  // '#lefsel',
  // '#lessee',
  // '#lesses',
  // '#loaded',
  // '#loafed',
  // '#lobale',
  // '#lobbed',
  // '#lobola',
  // '#lobolo',
  // '#lobosa',
  // '#lobose',
  // '#locale',
  // '#locals',
  // '#locoed',
  // '#locoes',
  // '#lolled',
  // '#loofas',
  // '#loosed',
  // '#looses',
  // '#losels',
  // '#losses',
  // '#oboles',
  // '#obolos',
  // '#obsede',
  // '#obsess',
  // '#odessa',
  // '#offals',
  // '#olacad',
  // '#olease',
  // '#oleose',
  // '#oodles',
  // '#osella',
  // '#oselle',
  // '#sabalo',
  // '#sabbed',
  // '#sabeca',
  // '#sables',
  // '#saccos',
  // '#sacela',
  // '#saddle',
  // '#salada',
  // '#salade',
  // '#salads',
  // '#salele',
  // '#sallee',
  // '#salloo',
  // '#salols',
  // '#sassed',
  // '#sasses',
  // '#sblood',
  // '#scalae',
  // '#scalds',
  // '#scaled',
  // '#scales',
  // '#scalfe',
  // '#scalls',
  // '#sclaff',
  // '#scoffs',
  // '#scolds',
  // '#scoloc',
  // '#seabed',
  // '#seabee',
  // '#sealed',
  // '#secale',
  // '#seccos',
  // '#secede',
  // '#secess',
  // '#seeded',
  // '#seeled',
  // '#seesee',
  // '#selfed',
  // '#selles',
  // '#sessed',
  // '#sobbed',
  // '#sobole',
  // '#socles',
  // '#sodded',
  // '#solace',
  // '#soleas',
  // '#soloed',
  // '#soodle',
  '#soosoo',
  '#sossle'
]
//
//
// const images = ['ff0000','ffff22','ffff33', '0000ff']
//



function delay(array) {
  if (!array.length) return

  const split = 2
  const head = array.slice(0, split)
  const tail = array.slice(split)

  head.forEach((image) => {
    image = image.slice(1)
    const wget = spawn('wget', [`http://placehold.it/4600x2000/${image}/${image}`, '-O', `${image}.png`]);

    wget.stdout.on('data', (data) => {
      // console.log(`stdout: ${data}`);
    });

    wget.stderr.on('data', (data) => {
      // console.log(`stderr: ${data}`);
    });

    wget.on('close', (code) => {
      console.log(`child process for image ${image} exited with code ${code}`);
    });
  })

  setTimeout(function() {
    delay(tail)
  }, 2000)

}

delay(images)
